### ISSUE TITLE
Paper and Code Release

### ISSUE THREAD

**Issue by wenzhengzeng** [qirui-chen/MultiHop-EgoQA#1]
Thank you for your nice work. Could you give an approximate date for the release of the full paper as well as the code? Thank you!

**Comment by qirui-chen** [comment]
Thank you for your interest! The link to our paper is [arXiv](https://arxiv.org/abs/2408.14469). The code is currently being organized and should be released within three weeks.

**Comment by wenzhengzeng** [comment]
Thank you!

**Comment by qirui-chen** [comment]
The codes have been released. Any suggestions are welcome.

**Comment by wenzhengzeng** [comment]
Thank you!
